/**
 * AI Insights Type Definitions
 *
 * Defines the structure for financial insights generated by rule-based
 * algorithms and enhanced with OpenAI GPT-4o natural language explanations.
 */

/**
 * Types of insights that can be generated
 */
export type InsightType =
  | 'budget_alert'        // Over-budget or approaching budget warnings
  | 'trend_analysis'      // Month-over-month spending comparisons
  | 'spending_pattern'    // Behavioral patterns (streaks, shared/personal shifts)
  | 'recommendation'      // AI-generated actionable advice
  | 'positive_feedback'   // Positive reinforcement for good habits

/**
 * Severity levels for visual coding and prioritization
 */
export type InsightSeverity =
  | 'critical'   // Red - Requires immediate attention (>30% over budget)
  | 'warning'    // Amber - Needs monitoring (10-30% over budget, large increases)
  | 'info'       // Stone - Informational (neutral trends, patterns)
  | 'positive'   // Green - Positive trends (spending down, on track)

/**
 * Main insight interface
 * Represents a single financial insight with all necessary data for display
 */
export interface Insight {
  id: string                    // Unique identifier
  type: InsightType             // Type of insight
  severity: InsightSeverity     // Severity for visual coding
  title: string                 // Short, actionable title (e.g., "Dining Budget Over")
  explanation: string           // Detailed explanation (2-3 sentences)
  score: number                 // Priority score (0-100, higher = more important)

  // Optional category reference
  category?: string             // Expense category this insight relates to

  // Optional metric data for display
  metric?: {
    current: number             // Current period value ($)
    previous?: number           // Previous period value ($)
    change?: number             // Absolute change ($)
    changePercent?: number      // Percentage change (%)
    budget?: number             // Budget limit (if applicable)
    percentUsed?: number        // Percentage of budget used
  }

  // Optional action steps (bulleted list for AI recommendations)
  actionSteps?: string[]

  // Optional call-to-action button
  cta?: {
    text: string                // Button text (e.g., "Review Budgets")
    href: string                // Link destination
  }
}

/**
 * Response from /api/insights/rules endpoint
 */
export interface RuleBasedInsightsResponse {
  insights: Insight[]
  metadata: {
    householdId: string
    month: string               // "YYYY-MM"
    generatedAt: string         // ISO timestamp
    dataPoints: {
      expenseCount: number
      budgetCount: number
      monthsOfData: number      // How many months of historical data available
    }
  }
}

/**
 * Response from /api/insights/generate endpoint (OpenAI-enhanced)
 */
export interface AIEnhancedInsightsResponse {
  insights: Insight[]
  metadata: {
    householdId: string
    month: string
    generatedAt: string
    cached: boolean             // Whether these insights were cached
    expiresAt: string           // When cache expires
  }
}

/**
 * Input data for insight generators
 */
export interface InsightGeneratorInput {
  // Current month data
  expenses: Array<{
    id: string
    amount: number
    category: string
    date: Date
    isShared: boolean
    userId: string
  }>

  budgets: Array<{
    id: string
    category: string
    amount: number
    userId: string | null
  }>

  users: Array<{
    id: string
    name: string
  }>

  stats: {
    totalSpent: number
    sharedExpenses: number
    spendingPerPerson: Array<{
      userId: string
      name: string
      total: number
      shared: number
      personal: number
    }>
    spendingByCategory: Array<{
      category: string
      amount: number
    }>
  }

  // Historical data (previous 3 months)
  previousMonths?: Array<{
    month: string
    totalSpent: number
    spendingByCategory: Array<{
      category: string
      amount: number
    }>
  }>

  // Context
  householdId: string
  currentMonth: string          // "YYYY-MM"
  daysIntoMonth: number         // How many days into current month
  daysLeftInMonth: number       // Days remaining in month
}

/**
 * Priority scoring factors (for documentation)
 */
export interface PriorityScoreFactors {
  financialImpact: number       // 0-40 points (40% weight)
  urgency: number               // 0-30 points (30% weight)
  actionability: number         // 0-20 points (20% weight)
  userEngagement: number        // 0-10 points (10% weight)
}
